version: "3.8"

services:
  pantry_supply_tracker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PACKAGE_DEVELOPMENT_MODE=-e
        - IMAGE_ENV=test
    env_file:
      - .env
    command: "pytest"
    ports:
      - ${HOST_PORT}:${SERVER_PORT}
    volumes:
      - ./pantry_supply_tracker:/app/pantry_supply_tracker