version: "3.8"

services:
  pantry_supply_tracker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - PACKAGE_DEVELOPMENT_MODE=-e
    env_file:
      - .env
    command: "python src/pantry_supply_tracker/main.py"
    ports:
      - ${HOST_PORT}:${SERVER_PORT}
    volumes:
      - ../src/pantry_supply_tracker:/app/src/pantry_supply_tracker