name: Build and Push Image
on: push
#  push:
 #   tags:
  #    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    name: Build and push image

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Get version from tag
        id: extract_version
        run: |
          echo ::set-output name=tag::$(echo ${{github.ref_name}} | sed "s/v//")

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/Schmaexxi/pantry_supply_tracker:${{steps.extract_version.outputs.tag}}
