name: Linting

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Linting
    steps:
    - name: Checkout commit
      uses: actions/checkout@v3
    - name: Set up Python 3.10.5
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.5
    - name: Install package
      run: pip install .
    - name: Install dev-requirements
      run: pip install -r dev_requirements.txt
    - name: black
      run: black --check .
    - name: flake8
      run: flake8 --max-line-length=100 ./pantry_supply_tracker
    - name: mypy
      run: mypy --strict ./pantry_supply_tracker