name: Pytest

on:
  pull_request:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest
    name: Test with pytest
    steps:
    - name: Checkout commit
      uses: actions/checkout@v3
    - name: Set up Python 3.10.5
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.5
    - name: Install package
      run: pip install .
    - name: Install pytest
      run: pip install --upgrade pip && pip install pytest
    - name: pytest
      run: pytest