name: Pytest

on:
  pull_request:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest
    name: Test with pytest
    steps:
    - name: Checkout commit
      uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: Install package
      run: pip install .
    - name: pytest
      run: pytest